services:
  watchrelaybot:
    image: ghcr.io/donnyfly/watchrelaybot:experimental
    container_name: watchrelaybot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
